### ISSUE TITLE
PRC January Assignment

### ISSUE THREAD

**Issue by lejeunerenard** [hoelzro/plack-middleware-recorder#11]
I have been assigned this module as part of the [2016 Pull Request Challenge](http://cpan-prc.org/). I was wondering if there were any issues or features you would like me to tackle in addition to the [PR I already submitted](https://github.com/hoelzro/plack-middleware-recorder/pull/10).

I saw #9 which is mostly fixed but requires tweaking for windows. I plan on attempting to fix that issue if I don't hear from you otherwise.

**Comment by hoelzro** [comment]
@lejeunerenard #9 would be good to work on; #8 would be nice if you could fix it.  Anything under https://metacpan.org/pod/Plack::Middleware::Recorder#FURTHER-IMPROVEMENTS would be a nice-to-have

**Comment by lejeunerenard** [comment]
Sorry couldn't get to this in time. I guess my one PR will have to suffice. If I can, I will look into the issue later.
