### ISSUE TITLE
Release 0.05?

### ISSUE THREAD

**Issue by eserte** [hoelzro/plack-middleware-recorder#12]
Comparing
http://matrix.cpantesters.org/?dist=Plack-Middleware-Recorder%200.05-TRIAL
and
http://matrix.cpantesters.org/?dist=Plack-Middleware-Recorder%200.04
suggests that the 0.05 should be released. Granted, it's not perfect, but it looks way better than the current stable release.

**Comment by hoelzro** [comment]
I just released 0.06!
